### ISSUE TITLE
stage目录下没有static目录

### ISSUE THREAD

**Issue by yanglaowu** [Abiel1024/vue-project#1]
npm run stage  和 npm run build 目录下生成的东西不一致

**Comment by Abiel1024** [comment]
@LayerYang 你可以截个图说明下吗？

 我在我本地的试了下是一样的：

![image](https://user-images.githubusercontent.com/21165482/42195556-f1ce4eb4-7eab-11e8-8008-507bd88e1300.png)
![image](https://user-images.githubusercontent.com/21165482/42195576-0a9f1874-7eac-11e8-923e-83344c1bdaf6.png)

**Comment by yanglaowu** [comment]
看了一下，是我脚手架版本的问题，更新了脚手架重新create的项目打包出来就是正确的。以前的beta更新到rc就没问题

**Comment by Abiel1024** [comment]
好的哈
