### ISSUE TITLE
请问原来的webpack.dev.config.js怎么配置到现在的vue.config.js中呢

### ISSUE THREAD

**Issue by Albertxiaoze** [Abiel1024/vue-project#2]
请问原来的webpack.dev.config.js怎么配置到现在的vue.config.js中呢

**Comment by Abiel1024** [comment]
@Albertxiaoze 在项目跟目录添加.env.dev文件，配置该文件中。可以参考这篇文章：https://github.com/Abiel1024/blog/issues/14
